name: Build and Deploy Website
on:
  push:
    branches:
      - main
      - target
  workflow_dispatch:
    branches:
      - main
  repository_dispatch:
    types: [new-profiling-results]

permissions:
  deployments: write
  contents: write

concurrency:
  # Skip build if a new build is triggered by new updates
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_pages_site:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch source branch contents
        run: |
          git checkout target
          git checkout main

      - name: Setup Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python requirements 
        run: pip install -r requirements.txt
      
      - name: Build website source
        run: python website_build/build_site.py -c -f target

      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean: True