name: Build and Deploy Website
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [new-profiling-results]

permissions:
  deployments: write
  contents: write

concurrency:
  # Skip build if a new build is triggered by new updates
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs-build:
    name: Build developer docs
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Doxygen
      run: brew install doxygen graphviz
      shell: bash

    - name: Run Doxygen
      run: doxygen Doxyfile
      shell: bash

    # Disabling jekyll ensures pages with underscores work on gh pages.
    - name: Create .nojekyll
      run: touch html/.nojekyll
      shell: bash

    - name: Upload the generated HTML
      uses: actions/upload-artifact@v3
      with:
        name: dev_docs_html_${{ github.sha }}
        path: html/*
        retention-days: 1

  profiling-build:
    name: Build profiling results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch source branch contents
        run: |
          git checkout target
          git checkout -

      - name: Setup Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python requirements 
        run: pip install -r requirements.txt
      
      - name: Build website source
        run: python website_build/build_site.py -c -f target

      - name: Upload the generated HTML
        uses: actions/upload-artifact@v3
        with:
          name: profiling_results_html_${{ github.sha }}
          path: build/*
          retention-days: 1

  # Only deploy the website on pushes to main
  # This allows the previous two jobs to be used as checks against PRs
  deploy-website:
    name: Deploy pages site
    runs-on: ubuntu-latest
    needs: [docs-build, profiling-build]
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch profiling results html
        uses: actions/download-artifact@v3
        with:
          name: profiling_results_html_${{ github.sha }}
          path: build/

      - name: Fetch developer docs html
        uses: actions/download-artifact@v3
        with:
          name: dev_docs_html_${{ github.sha }}
          path: dev

      - name: Move doxygen files into build folder
        run: mv dev/ build/

      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean: True